### ISSUE TITLE
JackIt runs fine once, then get the following error every time after, reboot resolves the issue

### ISSUE THREAD

**Issue by nullsession0x** [insecurityofthings/jackit#43]
Traceback (most recent call last):
  File "/usr/local/bin/jackit", line 252, in <module>
    cli()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/bin/jackit", line 182, in cli
    raise e
usb.core.USBError: [Errno 110] Operation timed out

**Comment by bucky67gto** [comment]
I get the same thing, but you can do without rebooting - just remove and reinsert the USB

**Comment by elnerd** [comment]
Try the --reset flag

**Comment by StringerB** [comment]
I'm having the same issue. Unplugging the USB appears to work the best for me.
